server:
  port: 8085

spring:
  application:
    name: ws-hub
  cloud:
    function:
      definition: process;sessionDownstream
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        process-in-0:
          destination: topic.websocket.message
        sessionDownstream-out-0:
          destination: topic.websocket.user.session
  profiles:
    include: rabbitmq


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true