spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  message:
    exchange:
      name: user.message.exchange
      type: topic
      durable: false # if true, the exchange will survive broker restarts. in development, we don't need this
