spring:
  application:
    name: websocket-hub
  cloud:
    function:
      definition: process
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        process-in-0:
          destination: chatapp.message


