server:
  port: 8085

spring:
  application:
    name: ws-hub
  cloud:
    function:
      definition: process
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        process-in-0:
          destination: chatapp.message


# session start: topic.user.session.start
# session end: topic.user.session.end

# in the feature these are 2 topics the ws-hub listen and process event
# topic.user.online
# topic.user.offline

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true